### ISSUE TITLE
Status command shows same statistic in every row

### ISSUE THREAD

**Issue by LoeschMaximilian** [mightymatth/arcli#22]
Example Output
```
[xxx] Maximilian Lösch (xxx)
 PERIOD      HOURS  H/LOG  # OF I  # OF P
 Today       394.8  3.9        13       8
 Yesterday   394.8  3.9        13       8
 This Week   394.8  3.9        13       8
 Last Week   394.8  3.9        13       8
 This Month  394.8  3.9        13       8
 Last Month  394.8  3.9        13       8
```
Some Information redacted.
I use a self-built version of the master branch without any modifications.

**Comment by mightymatth** [comment]
I cannot see your specific user data, but you can try it yourself if there is a problem in CLI or Redmine itself.

We get these data by accessing Redmine issues page and applying filters:

$REDMINE_URL/issues?**spent_on=%s&user_id=me&limit=200**

where `spent_on` values are:
https://github.com/mightymatth/arcli/blob/e6ec057d46f26aac83ab00aa44c6f5f0f378ccc4/cmd/status.go#L132-L139

You can try to change those values in the browser and see if you have the same results.

**Comment by LoeschMaximilian** [comment]
Thanks, i checked what you mentioned.

I forgot that we work on a older version of easyRedmine, which would explain some of the issues.

I am going to close this issue, as it is more a problem on our end.
